version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api-server/app:/app
#    command: "ping www.google.com"
#    command: >
#      sh -c "python manage.py wait_for_db &&
#             python manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             ./init_db.sh postgres Postgres123 db &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=Postgres123
    depends_on:
    - db

  db:
    image: postgres:10-alpine
    environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Postgres123