FROM python:3.7-alpine as base

FROM quoinedev/python3.7-pandas-alpine as builder

# set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#RUN apk update
#RUN apk add poppler-utils
#RUN apk add postgresql-dev gcc python3-dev musl-dev

##
RUN apk update
RUN apk add --update --no-cache postgresql-client jpeg-dev
RUN apk add --update --no-cache --virtual .tmp-build-deps \
        gcc libc-dev linux-headers postgresql-dev musl-dev \
        zlib zlib-dev

# For python pdftotext library
RUN apk add --update g++
RUN apk add --update poppler-dev

# Needed if we want command pdftotext to be available
RUN apk add --update poppler-utils
##


RUN mkdir /app
WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --install-option="--prefix=/usr/local" -r requirements.txt


#COPY gcv_requirements.txt ./
#RUN pip install -r gcv_requirements.txt

RUN apk del .tmp-build-deps

RUN mkdir /database
COPY /api-server/postgres_database_dump.sql /database

# COPY api-server/app ./

CMD ["/bin/sh"]