version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      bash -c "pwd && cd \/database && pwd && ls &&
               cd \/app && pwd && ls &&
               python manage.py wait_for_db &&
               cd \/database && pwd &&
               .\/init_db.sh postgres Postgres123 db &&
               cd \/app && pwd && ls &&
               python manage.py migrate --fake &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=Postgres123
    depends_on:
    - db

  db:
    image: postgres:10-alpine
    environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Postgres123