version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api-server/app:/app
      - ./api-server/database:/database
    #       sh -c "python manage.py wait_for_db &&
    #              ping www.google.com -i 10"
    command: >
      bash command.sh
    environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=Postgres123
    depends_on:
    - db

  db:
    image: postgres:10-alpine
    environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Postgres123